-- CreateTable
CREATE TABLE `DRESSING_REQS` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `req_services` VARCHAR(191) NOT NULL,
    `req_duration` VARCHAR(191) NOT NULL,
    `req_price` DECIMAL(10, 2) NOT NULL,
    `req_status` BOOLEAN NOT NULL,
    `req_client` VARCHAR(191) NOT NULL,
    `req_colab` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `DRESSING_REQS` ADD CONSTRAINT `DRESSING_REQS_req_client_fkey` FOREIGN KEY (`req_client`) REFERENCES `DRESSING_CLIENTES`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DRESSING_REQS` ADD CONSTRAINT `DRESSING_REQS_req_colab_fkey` FOREIGN KEY (`req_colab`) REFERENCES `DRESSING_COLABORADORES`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
