-- DropForeignKey
ALTER TABLE `DRESSING_REQS` DROP FOREIGN KEY `DRESSING_REQS_req_colab_fkey`;

-- AlterTable
ALTER TABLE `DRESSING_REQS` MODIFY `req_status` BOOLEAN NOT NULL DEFAULT false,
    MODIFY `req_colab` VARCHAR(191) NULL;

-- AddForeignKey
ALTER TABLE `DRESSING_REQS` ADD CONSTRAINT `DRESSING_REQS_req_colab_fkey` FOREIGN KEY (`req_colab`) REFERENCES `DRESSING_COLABORADORES`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
